# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev_hello_world',
                'doc_host': 'https://muhammad-asif78.github.io',
                'git_url': 'https://github.com/muhammad-asif78/nbdev_hello_world',
                'lib_path': 'nbdev_hello_world'},
  'syms': { 'nbdev_hello_world.calculator': { 'nbdev_hello_world.calculator.add': ('core.html#add', 'nbdev_hello_world/calculator.py'),
                                              'nbdev_hello_world.calculator.calculator_logic': ( 'core.html#calculator_logic',
                                                                                                 'nbdev_hello_world/calculator.py'),
                                              'nbdev_hello_world.calculator.divide': ( 'core.html#divide',
                                                                                       'nbdev_hello_world/calculator.py'),
                                              'nbdev_hello_world.calculator.foo': ('core.html#foo', 'nbdev_hello_world/calculator.py'),
                                              'nbdev_hello_world.calculator.multiply': ( 'core.html#multiply',
                                                                                         'nbdev_hello_world/calculator.py'),
                                              'nbdev_hello_world.calculator.subtract': ( 'core.html#subtract',
                                                                                         'nbdev_hello_world/calculator.py')},
            'nbdev_hello_world.core': {'nbdev_hello_world.core.foo': ('core.html#foo', 'nbdev_hello_world/core.py')}}}
