"""Fill in a module description here"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = ['add', 'subtract', 'multiply', 'divide', 'calculator_logic', 'foo']

# %% ../nbs/00_core.ipynb 2
def add(a, b):
    return a + b

#|export
def subtract(a, b):
    return a - b

#|export
def multiply(a, b):
    return a * b

#|export
def divide(a, b):
    if b == 0:
        return "Error: Division by zero"
    return a / b

#|export
def calculator_logic(a, b, op):
    if op == '+':
        return add(a, b)
    elif op == '-':
        return subtract(a, b)
    elif op == '*':
        return multiply(a, b)
    elif op == '/':
        return divide(a, b)
    else:
        return "Invalid operator"


# %% ../nbs/00_core.ipynb 4
def foo(): pass
